### ISSUE TITLE
AP not presented/visible, D1 Mini Flashing rapidly

### ISSUE THREAD

**Issue by Tollbringer** [achmed20/GaragePack#1]
I have flashed the D1 Mini2 times, neither time is the Wifi AP presented. I am not sure what I am doing wrong. I can see the D1 Light flashing rapidly.

ESP seems to be resetting itself rapidly.

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v8b899c12
~ld
Garagepack Version 0.8
loading settings failed
Running SetupMode

 I hope this helps!

**Comment by achmed20** [comment]
sounds like you forgot to flash the file system.

**Comment by SirRedZ** [comment]
I am very new to this - Any help would be appreciated.

**Comment by Tollbringer** [comment]
![vs_code_upload](https://user-images.githubusercontent.com/44956412/65154557-b2b80800-d9f9-11e9-8769-f6b8dd415a53.JPG)
Ok Got it!

I tried GitPod and Atom- neither supported your instructions. VSCode works clearly as expected. Also note: Firefox browser will not bring up the GUI for config after connection to the AP. This looks very well done! Thanks very much for sharing!

[-=SrZ=-]
